# version format
version: 2.0.0.{build}

# Do not build on tags
skip_tags: true


build_script:
  - cd Build
  - Package.build.cmd

artifacts:
  - path: artifacts\*.nupkg
  
deploy:
  provider: NuGet
  server:
  api_key:
    secure: cRKDqHqagUzMgXLZ971fBXwpacf44O7jsIk7hfeLNo75kShTMknWjQfWLGxgKIPt
  artifact: /.*\.nupkg/