# version format
version: 2.0.0.{build}

image: Visual Studio 2017

# Do not build on tags
skip_tags: true

before_build:
  - ps: nuget restore MCFly.sln
  
build_script:
  - msbuild build/Package.build.xml

artifacts:
  - path: artifacts\*.nupkg
  
deploy:
  provider: NuGet
  server:
  api_key:
    secure: pSnnMzX7vNehQs7wWAPaZWMYmNv+D0UYrwwp5+ncdhYVifcAkNfY4fIHR/GDeEBi
  artifact: /.*\.nupkg/
